kind: pipeline
type: docker
name: Analysis
steps:
- name: fetch
  image: docker:git
  commands:
    - git fetch --tags
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
    usingProperties: true
- name: build
  image: golang
  commands:
    - go build .
- name: release
  image: goreleaser/goreleaser
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  commands:
    - goreleaser release
  when:
    event:
      - tag
