kind: pipeline
type: docker
name: gtop

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags
  when:
    event:
    - tag
- name: sonar analysis
  image: kytay/sonar-node-plugin 
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
    sonar_project_settings: ./sonar-project.properties
- name: build
  image: golang
  commands:
  - go build .
- name: release
  image: goreleaser/goreleaser
  environment:
    AUR_KEY:
      from_secret: aur_key
    GITHUB_TOKEN:
      from_secret: github_token
  commands:
  - goreleaser release
  when:
    event:
    - tag

      #---
      #kind: pipeline
      #type: docker
      #name: docker-build
      #
      #steps:
      #- name: build-tag
      #  image: plugins/docker
      #  failure: ignore
      #  settings:
      #    username: mjehanno
      #    password:
      #      from_secret: docker_token
      #    tags:
      #    - latest
      #    - ${DRONE_TAG}
      #    repo: mjehanno/vhs
      #    dockerfile: vhs.Dockerfile
      #    force_tag: true
      #    squash: true
      #  when:
      #    event:
      #    - tag
      #
      #---
      #kind: pipeline
      #type: docker
      #name: vhs
      #
      #steps:
      #- name: gif-generation
      #  image: mjehanno/vhs:latest
      #  failure: ignore
      #  privileged: true
      #  commands:
      #  - vhs demo.tape
      #  - git config --global user.name="mJehanno"
      #  - git config --global user.email="mathob.jehanno@hotmail.fr"
      #  - git add .
      #  - "git commit -m 'feat(vhs): update demo.gif for documentation on usage'"
      #  - echo $SSH_KEY >> /home/vhs/.ssh/git
      #  - echo "Host github.com" >> /home/vhs/.ssh/config
      #  - echo "  User git"
      #  - echo "  IdentityFile /home/vhs/.ssh/git"
      #  - git push origin main
      #  environment:
      #    SSH_KEY:
      #      from_secret: vhs_commit
      #  when:
      #    event:
      #      - tag
      #depends_on:
      #- docker-build
