kind: pipeline
type: docker
name: Analysis
steps:
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
    usingProperties: true
- name: build
  image: golang
  commands:
    - go build .
- name: release
  image: golang
  commands:
    - go install github.com/goreleaser/goreleaser@latest
    - goreleaser release
  when:
    event:
      - tag
