kind: pipeline
type: docker
name: gtop

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags
  when:
    event:
    - tag
- name: sonar analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
    usingProperties: true
- name: build
  image: golang
  commands:
  - go build .
- name: release
  image: goreleaser/goreleaser
  environment:
    AUR_KEY:
      from_secret: aur_key
    GITHUB_TOKEN:
      from_secret: github_token
  commands:
  - echo $AUR_KEY > ../ssh-key
  - goreleaser release
  when:
    event:
    - tag

---
kind: pipeline
type: docker
name: vhs

steps:
- name: gif-generation
  image: mjehanno/vhs
  environment:
    KEY:
      from_secret: vhs_commit
  commands:
  - go install github.com/charmbracelet/vhs@latest
  - mkdir -p ~/.ssh
  - echo $KEY > ~/.ssh/vhs_key
  - echo 'Host github.com-gtop' >> ~/.ssh/config
  - echo '      Hostname github.com' >> ~/.ssh/config
  - echo '      IdentityFile=/home/vhs/.ssh/vhs_key' >> ~/.ssh/config
  - vhs demo.tape
  - git add demo.gif
  - "git commit -m 'feat(vhs): adds generated demo.gif"
  - git push origin main
  when:
    event:
    - tag
